[2024-01-05T20:31:00.780+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T20:30:00+00:00/task_id=PostgresTable permission to 509
[2024-01-05T20:31:00.781+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T20:30:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T20:30:00+00:00/task_id=PostgresTable'
[2024-01-05T20:31:00.813+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T20:30:00+00:00/task_id=PostgresTable permission to 509
[2024-01-05T20:31:00.814+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T20:30:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T20:30:00+00:00/task_id=PostgresTable'
[2024-01-05T20:31:00.871+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: User_counter.PostgresTable scheduled__2024-01-05T20:30:00+00:00 [queued]>
[2024-01-05T20:31:00.881+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: User_counter.PostgresTable scheduled__2024-01-05T20:30:00+00:00 [queued]>
[2024-01-05T20:31:00.882+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-05T20:31:00.898+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): PostgresTable> on 2024-01-05 20:30:00+00:00
[2024-01-05T20:31:00.903+0000] {standard_task_runner.py:60} INFO - Started process 1394 to run task
[2024-01-05T20:31:00.907+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'User_counter', 'PostgresTable', 'scheduled__2024-01-05T20:30:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/User_counter.py', '--cfg-path', '/tmp/tmp95ts_p43']
[2024-01-05T20:31:00.910+0000] {standard_task_runner.py:88} INFO - Job 51: Subtask PostgresTable
[2024-01-05T20:31:00.964+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T20:30:00+00:00/task_id=PostgresTable permission to 509
[2024-01-05T20:31:00.964+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T20:30:00+00:00/task_id=PostgresTable permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=User_counter/run_id=scheduled__2024-01-05T20:30:00+00:00/task_id=PostgresTable'
[2024-01-05T20:31:00.966+0000] {task_command.py:423} INFO - Running <TaskInstance: User_counter.PostgresTable scheduled__2024-01-05T20:30:00+00:00 [running]> on host e91b89fa10db
[2024-01-05T20:31:01.072+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='User_counter' AIRFLOW_CTX_TASK_ID='PostgresTable' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T20:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T20:30:00+00:00'
[2024-01-05T20:31:01.073+0000] {sql.py:276} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users_count (
            count_id SERIAL PRIMARY KEY,
            count INTEGER NOT NULL,
            date VARCHAR NOT NULL);
[2024-01-05T20:31:01.083+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-01-05T20:31:01.093+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-01-05T20:31:01.098+0000] {sql.py:432} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users_count (
            count_id SERIAL PRIMARY KEY,
            count INTEGER NOT NULL,
            date VARCHAR NOT NULL);, parameters: None
[2024-01-05T20:31:01.108+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=User_counter, task_id=PostgresTable, execution_date=20240105T203000, start_date=20240105T203100, end_date=20240105T203101
[2024-01-05T20:31:01.161+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-05T20:31:01.186+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
