[2024-01-06T15:29:50.671+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=CountCleaner/run_id=manual__2024-01-06T15:29:49.624250+00:00/task_id=Clean_data permission to 509
[2024-01-06T15:29:50.671+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=CountCleaner/run_id=manual__2024-01-06T15:29:49.624250+00:00/task_id=Clean_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=CountCleaner/run_id=manual__2024-01-06T15:29:49.624250+00:00/task_id=Clean_data'
[2024-01-06T15:29:50.750+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=CountCleaner/run_id=manual__2024-01-06T15:29:49.624250+00:00/task_id=Clean_data permission to 509
[2024-01-06T15:29:50.753+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=CountCleaner/run_id=manual__2024-01-06T15:29:49.624250+00:00/task_id=Clean_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=CountCleaner/run_id=manual__2024-01-06T15:29:49.624250+00:00/task_id=Clean_data'
[2024-01-06T15:29:50.835+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: CountCleaner.Clean_data manual__2024-01-06T15:29:49.624250+00:00 [queued]>
[2024-01-06T15:29:50.857+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: CountCleaner.Clean_data manual__2024-01-06T15:29:49.624250+00:00 [queued]>
[2024-01-06T15:29:50.858+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-06T15:29:50.893+0000] {taskinstance.py:2192} INFO - Executing <Task(PostgresOperator): Clean_data> on 2024-01-06 15:29:49.624250+00:00
[2024-01-06T15:29:50.907+0000] {standard_task_runner.py:60} INFO - Started process 263 to run task
[2024-01-06T15:29:50.922+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'CountCleaner', 'Clean_data', 'manual__2024-01-06T15:29:49.624250+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/Data_Clean.py', '--cfg-path', '/tmp/tmpo6hpvq4x']
[2024-01-06T15:29:50.967+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask Clean_data
[2024-01-06T15:29:51.138+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=CountCleaner/run_id=manual__2024-01-06T15:29:49.624250+00:00/task_id=Clean_data permission to 509
[2024-01-06T15:29:51.139+0000] {logging_mixin.py:188} INFO - Failed to change /opt/***/logs/dag_id=CountCleaner/run_id=manual__2024-01-06T15:29:49.624250+00:00/task_id=Clean_data permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=CountCleaner/run_id=manual__2024-01-06T15:29:49.624250+00:00/task_id=Clean_data'
[2024-01-06T15:29:51.168+0000] {task_command.py:423} INFO - Running <TaskInstance: CountCleaner.Clean_data manual__2024-01-06T15:29:49.624250+00:00 [running]> on host 6edae0fffd8a
[2024-01-06T15:29:51.396+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='CountCleaner' AIRFLOW_CTX_TASK_ID='Clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T15:29:49.624250+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-06T15:29:49.624250+00:00'
[2024-01-06T15:29:51.397+0000] {sql.py:276} INFO - Executing: TRUNCATE  users_count;
[2024-01-06T15:29:51.415+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-01-06T15:29:51.435+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-01-06T15:29:51.441+0000] {sql.py:432} INFO - Running statement: TRUNCATE  users_count;, parameters: None
[2024-01-06T15:29:51.468+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=CountCleaner, task_id=Clean_data, execution_date=20240106T152949, start_date=20240106T152950, end_date=20240106T152951
[2024-01-06T15:29:51.512+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-06T15:29:51.544+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
